framework:
  mailer:
    # dsn: "%env(MAILER_DSN)%"
    dsn: 'smtp://%env(MAILGUN_SMTP_LOGIN)%:%env(MAILGUN_SMTP_PASSWORD)%@%env(MAILGUN_SMTP_SERVER)%:%env(MAILGUN_SMTP_PORT)%?verify_peer=0&region=us'
        envelope:
            sender: '%env(MAILGUN_SMTP_LOGIN)%'
        headers:
            From: '%env(APP_NAME)% <%env(MAILGUN_SMTP_LOGIN)%>'
    # message_bus: false
